version: '3.9'

services:
  mongo:
    image: mongo:5.0.2
    restart: 'unless-stopped'
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_zira:/data/db

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis_zira:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - postgres_zira:/var/lib/postgresql/data

volumes:
  mongodb_zira:
  redis_zira:
  postgres_zira:
